### ISSUE TITLE
Installation Problem!

### ISSUE THREAD

**Issue by TheUncannyScrub** [Rantanen/node-opus#30] opened 2017-04-07 14:25 UTC
D:\Software Development\Discord Bot\JS>npm install discord.js node-opus --save

> ref@1.3.4 install D:\Software Development\Discord Bot\JS\node_modules\ref
> node-gyp rebuild

D:\Software Development\Discord Bot\JS\node_modules\ref>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Software Development\Discord Bot\JS\node_modules\ref
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
D:\Software Development\Discord Bot\JS
+-- discord.js@11.0.0
+-- UNMET PEER DEPENDENCY erlpack@hammerandchisel/erlpack#master
+-- UNMET DEPENDENCY node-opus@latest
+-- UNMET PEER DEPENDENCY opusscript@0.0.3
`-- UNMET PEER DEPENDENCY uws@0.14.1

npm WARN enoent ENOENT: no such file or directory, open 'D:\Software Development
\Discord Bot\JS\package.json'
npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#ma
ster but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was ins
talled.
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed
.
npm WARN JS No description
npm WARN JS No repository field.
npm WARN JS No README data
npm WARN JS No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js" "node-opus" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Software Development\Discord Bot\JS\npm-debug.log

D:\Software Development\Discord Bot\JS>

**Comment by Rantanen** [comment] 2017-04-07 14:44
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

https://github.com/felixrieseberg/windows-build-tools

**Comment by TheUncannyScrub** [comment] 2017-04-07 14:47
Thanks, but im really new to this, IE: started 3 days ago. What do i do with that link?

**Comment by Rantanen** [comment] 2017-04-07 15:22
The `README.md` there should have instructions.

https://github.com/felixrieseberg/windows-build-tools/blob/master/README.md

But I guess you found those as you closed this issue. :)

**Comment by TheUncannyScrub** [comment] 2017-04-07 20:03
wellll... i followed the readme and i still get an error

**Comment by TheUncannyScrub** [comment] 2017-04-07 20:07
D:\Software Development\Discord Bot\JS>npm install node-opus --save

> ref@1.3.4 install D:\Software Development\Discord Bot\JS\node_modules\ref
> node-gyp rebuild


D:\Software Development\Discord Bot\JS\node_modules\ref>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [D:\Software Development\Discord Bot\JS\node_modules\ref\build\bindi
ng.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [D:\Software Development\Discord Bot\JS\node_modules\ref\build
\binding.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Software Development\Discord Bot\JS\node_modules\ref
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\Software Development
\Discord Bot\JS\package.json'
npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#ma
ster but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was ins
talled.
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed
.
npm WARN JS No description
npm WARN JS No repository field.
npm WARN JS No README data
npm WARN JS No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-opus" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Software Development\Discord Bot\JS\npm-debug.log

**Comment by Rantanen** [comment] 2017-04-07 21:05
This is caused by https://github.com/TooTallNate/ref package failing to build on Windows. Unfortunately I don't really do any node development on Windows so can't help here.

This isn't the first issue where this has been the case. This might be for reasons such as `ref` being the first package that npm attempts to compile (and thus it fails early on that) or then `ref` has issues which there [seem to be](https://github.com/TooTallNate/ref/issues).

In any case I published version 0.2.6 of `node-opus` which makes `ogg-packet` (and thus `ref`) an optional package. This does mean that the `Decoder` and `Encoder` functionality will not be available in the case `ogg-packet` fails to install, but it should still allow the use of `OpusEncoder` in these cases.

Can you try installing the 0.2.6 version? `npm install node-opus` should do the trick.

**Comment by Rantanen** [comment] 2017-04-07 21:09
This could also be due to https://github.com/felixrieseberg/windows-build-tools/issues/9

Do you have a proper Visual Studio installed locally instead of just the VC++ tools from the windows-build-tools package? Reading through the comments, these two are mutually exclusive. If you have Visual Studio installed separately, the VC++ tools won't install.

When installing Visual Studio, it will not install the C++ compiler by default. I believe this is what node-gyp tries to use here.

If this is the case, can you run the Visual Studio installer again and modify the installation to include the Visual C++ compiler?

**Comment by TheUncannyScrub** [comment] 2017-04-07 21:17
on that last point, is there anyway to add it because i installed VS 2015 WAAAYY before this project

**Comment by Rantanen** [comment] 2017-04-07 21:20
You can run the VS2015 installer again. It should prompt you to modify the installation, at which point you should get the chance to enable the C++ toolset. Once you progress, it'll download that and add it to your existing VS2015 installation.

**Comment by TheUncannyScrub** [comment] 2017-04-07 21:22
ok, i dont think i kept the installer, lets hope i can find it on their website

**Comment by TheUncannyScrub** [comment] 2017-04-07 21:26
https://gyazo.com/839d7ac4aeb623f19a9d5fa94cce450e would any of these do?

**Closed as completed** 2017-05-01 18:26 UTC

**Comment by Rantanen** [comment] 2017-05-01 20:14
Oh, sorry, had missed that last message.

I don't know which edition of VS2015 you got so I can't really comment on that anyway.

**Comment by TheUncannyScrub** [comment] 2017-05-02 02:04
Ahh, no worries, i got it running on an ubuntu vps, thanks anyways!


________________________________

**Comment by felipejacuru** [comment] 2020-02-14 23:03
What?
